### ISSUE TITLE
Frequent disconnected from Redis on Heroku

### ISSUE THREAD

**Issue by ch33foong** [akira/exq#253]
Hi there,

Ever since upgraded to 0.8.4, i have notice that the following message appears frequently on Heroku:

`02:34:54.996 [error] Disconnected from Redis (ec2-53-224-240-164.compute-1.amazonaws.com:7269): TCP connection closed`

However it will quickly reconnect back to redis

`02:34:55.506 [info] Reconnected to Redis (ec2-53-224-240-164.compute-1.amazonaws.com:7269)`

I have upgraded to 0.8.6, it is still happening. 

This happens about every 5 minutes, looks like a preset interval. Is this normal behaviour?

**Comment by akira** [comment]
Could it be due to the Heroku Redis timeout setting which is 5 minutes?

https://devcenter.heroku.com/articles/heroku-redis#timeout

Most likely this was happening before, but perhaps a newer version of the Redis driver is printing more information than before (I would compare the Redix version before and after).  It doesn't look like it's causing any issues, so probably just an informational message. The timeout could be extended / disabled also, but I wouldn't do that unless you are seeing issues.

**Comment by ch33foong** [comment]
I think you are right, strange that it logged as error. It does not cause any issue though :)
