### ISSUE TITLE
Is there a limit to how long a worker can spend processing a job?

### ISSUE THREAD

**Issue by lpil** [akira/exq#259]
Hello!

Thanks for this library! Looks like a good fit for my problem, and the code looks very nice. I have a couple of questions.

Is there a limit to how long a worker can spend processing a job?

If not is there a mechanism for detecting when a node has died and left jobs uncompleted? I may be reading the code incorrectly but it seems that it is the responsibility of a node to come back online and re-queue the jobs itself. What happens if the node is gone forever? Or is assigned a new identifier (say if we are using a container based solution such as K8s).

Thanks,
Louis

**Comment by akira** [comment]
There is no limit on how long workers can spend working. 

There is a mechanism for detecting downed nodes. But you are correct, it is the same node that comes up and re-queues the jobs itself. So that is correct, this doesn't work well for dynamic environments like K8s, unless there is a finite list of notes that are used (same node ID is used when it comes back up). 

If you look at Sidekiq (pro version), this is similar to the "reliable fetch" algorithm. 
https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server

This would have to be changed to use a heartbeat mechanism - this is something we've talked about but I don't have an update on when this would be implemented.

**Comment by lpil** [comment]
Great, thank you. Would you mind if I added this to the docs somewhere? If so, is there a particular place that would be good to put this information?

I like the idea of using a heartbeat, I was thinking about doing something like this.

**Comment by akira** [comment]
Sure, README would be good, maybe around this section:

https://github.com/akira/exq/blob/master/README.md#configuring-node-identifier-if-deployed-on-heroku

Thanks!
