### ISSUE TITLE
Priority job queue

### ISSUE THREAD

**Issue by ahmadferdous** [akira/exq#279]
Having read the documentation, I got the impression that the job queue that the workers receive job from is FIFO. In many applications, the jobs have priority associated. If I want to make job queue type configurable (FIFO, priority queue), how much design change do you think one would have to make?

**Comment by akira** [comment]
Right now there is no support for priority queue - the Redis structure is a list that is not prioritized. For different priorities, the recommended approach is to use multiple queues. You can specify concurrency per queue, so you can have different queues that are various priorities.

**Comment by ahmadferdous** [comment]
Thanks for your response.

With exq, is it possible to have one worker (or a pool or workers doing the same thing) that all consume from the same set of job queues? For example, let's assume we have 3 queues for 3 different priorities (low, medium, high) for the same kind of job. We have 2 instances of the same worker, who will get jobs according to priority. So, jobs in high priority will be executed first. Jobs in medium queue will be processed only if there's nothing in high priority queue. This kind of scenario is relevant when we have rate limiting constraint and we want to serve high priority clients first. 

I could not figure out the answer from README file and that's why I'm asking here.

**Comment by johnnyshields** [comment]
Ruby's DelayedJob library implements this well. You can set priority as a number per job, and you can also have a default priority defined for each queue in the config. The worker pool will work highest priority jobs first.

**Comment by akira** [comment]
The current design is different than the ones mentioned such as DelayedJob since this library sets the concurrency per queue and not globally. This means that each worker only looks at the queue level concurrency, and there are no shared workers that are grabbing items from multiple queues. You can set concurrency per queue and set a higher / lower level for queue depending on priority, but that is not exactly same as what is mentioned above.
