### ISSUE TITLE
Redis Connections Per Concurrent Worker?

### ISSUE THREAD

**Issue by johnnyji** [akira/exq#297]
Hi there,

I was wondering if there's anywhere that documents how many Redis connections exist for each concurrent worker? I run on Heroku Redis and my fear is that if I set `concurrency: 500`, it will at some point reach 500 Redis connections (easily breaking my Heroku limit).

I didn't seem to find any section that documents the relation between Redis connections and Exq workers, or if there's a way to cap connections? I would really appreciate it if someone could clear this up for me.

Thank you for the amazing library 👍 

- Johnny

**Comment by akira** [comment]
Concurrent workers do not use extra connections. There are 2 connections
per Exq instance and those connections are shared for that node regardless
of how many concurrent workers, so in your case you should be fine. I would
watch out for exhausting your database connection pool since that is
limited and usually something like 20-50 connections.
