### ISSUE TITLE
Redis failover without sentinel

### ISSUE THREAD

**Issue by deepfryed** [akira/exq#381]
Currently trying to solve an issue with AWS Elasticache failover that uses DNS change for a failover leaving Exq connected to a read replica - there is no explicit way of catching this and reconnecting in Exq at the moment since the failures happen before a job is dequeued and dispatched (cannot use middleware).

Is there a recommended approach to handling this ? I'm adding a very nasty workaround in our application by adding a custom logging backend to look for specific error message, stopping the Redix process and letting the supervisor bring a new one up that reconnects correctly to the new primary.

**Comment by ananthakumaran** [comment]
What happens to Exq when the failover happens, does it continuously retry?

> I'm adding a very nasty workaround in our application by adding a custom logging backend to look for specific error message, stopping the Redix process and letting the supervisor bring a new one up that reconnects correctly to the new primary.

A bit less nasty workaround would be using `ROLE` to check the server role periodically and restart if it's a slave

**Comment by deepfryed** [comment]
@ananthakumaran yeah Exq keeps retrying and Redix keeps raising the error.

> A bit less nasty workaround would be using ROLE command to check the server role periodically and restart if it's a slave

Yeah that'd work too, I'll have to use the same Redix connection that Exq uses - but it'd be good to update Exq to handle such a scenario.

**Comment by ananthakumaran** [comment]
Just to clarify, When Exq starts, it will check the redix connection and if it's not able to connect, it will quit right away. Otherwise it enters into the dequeue & dispatch loop. If any redix error occurred it will back off and retry.

The assumption here is, redix will eventually recover from the error by itself. Which is the case for connection failure and sentinel based failovers.

And what elasticache doing here seems to be non-standard. Usually (in sentinel setup at least) all the connections will get closed from the server side, which will force a reconnection.

I don't know who is responsible here

1) elasticache server should close the client connections on failover?
2) redix should handle this? (in which case, the recovery will work properly everywhere, not only with Exq)
3) Exq, killing the redix process might work, but it might not be straightforward. we need to know when to kill exactly (only for this kind of scenario) and we have to make sure we don't restart it too many times (otherwise it might cause the supervisor itself to restart etc)

**Comment by deepfryed** [comment]
> And what elasticache doing here seems to be non-standard.

Yes, but it's consistent with how they do DNS failovers for other services.
Applications are expected to handle these - not sure if this is because
Redis sentinel wasn't available when Elasticache Redis was build by AWS.

> I don't know who is responsible here

Ruling (1) out due to above, it's going to be Exq's responsibility to
handle errors with operations on a READONLY redis instance. Redix doesn't
care if you're connected to primary or a replica - since it's a valid mode
of operation, i.e. using a readonly replica for read scaling.

I'm looking into this, I'll have a PR for review soon if you're happy with
above.
