### ISSUE TITLE
Create API for parallelize job Enqueue

### ISSUE THREAD

**Issue by mrcdll** [akira/exq#388]
We are using Exq for processing events coming from http request.

We had some issue with Exq.Enqueuer timing out when we reached request spikes over 10k.
```
Elixir.ErlangError · Erlang error: {:timeout, {GenServer, :call, [Exq, {:enqueue, "gmail_webhook", Pathfinder.Gmail.WebhookPostJob, [args]}}
```

The problem was resolved pooling Exq.Enqueuer processes with poolboy.

Would you be interested into wrapping the feature into a dedicated interface?

**Comment by ananthakumaran** [comment]
Looking at the current code, we seem to unnecessarily serialize the enqueue step. Exq.Enqueuer.Server makes a request to redis and waits for reply **within** the gen_server loop. It only keeps the redis pid and namespace in the state. Ideally we should try to reduce the time spent inside the singleton gen_server loop. We could use a Agent which stores the pid/namespace. From the caller process do a lookup to get the pid/namespace and then make the redis request. This would remove the bottleneck at the Enqueuer level and likely Redix process might become the next bottleneck.

**Comment by mrcdll** [comment]
Correct, and Redis handled the load pretty well.

Is it fine if I go ahead and open a PR?

**Comment by ananthakumaran** [comment]
Yes, please go ahead

**Comment by sb8244** [comment]
I've done some work sharding Redix in the past. The [recommended approach](https://hexdocs.pm/redix/real-world-usage.html) is a name based pool. This works well when you're the direct Redix consumer, because you can pick one of the Redix and you get "pooling" in a way (I call this sharding).

Would a similar approach to the Enqueuer API be worth it? In that path, the Enqueuer remains serialized, but there is a sharded pool of Enqueuers, each with their own Redix connection. It's extremely important to have a pool of Redix connections, so this would be advantageous. I'm not sure how I'd go about sharding Redix unless it was configurable through Exq, maybe with a behavior.

It would be great if Exq handled all of this for the consumer, sort of like Phoenix PubSub does with its sharded process approach.

**Comment by ananthakumaran** [comment]
@sb8244 agree with sharding. Native sharding support would be nice. But we should first go for the low hanging fruit and remove the unnecessary serialize step we are introducing at Exq.

> Redix is built to handle multiple Elixir processes sending commands to Redis through it at the same time. It takes advantage of TCP being a full-duplex protocol (bytes are sent in both directions, often at the same time) so that the TCP stream has bytes flowing in both directions (to and from Redis). For example, if two Elixir processes send a PING command to Redis via Redix.command/2, Redix will send both commands to Redis but will concurrently start listening for the reply to these commands; at a given point, both a PING command as well as the PONG response to a previous PING could be flowing in the TCP stream of the socket that Redix is using.

Redix pipeline concurrent requests and it works pretty well throughput wise. Any help with testing #390 would be appreciated.

**Comment by sb8244** [comment]
I'll run it through the benchmark I did the other day
