### ISSUE TITLE
Exq perform finish all poolboy instances

### ISSUE THREAD

**Issue by EdoardoLopez** [akira/exq#435]
Hi i’m using Exq library, and a standalone poolboy implementation, i need poolboy to encode some videos files and the Exq to merge all files status progress, i need 3 pools to (sd, hd, fhd).
For example i run a Exq job and call 3 pools from poolboy to encode files, all ok from here, but when the Exq job finish all poolboy instances finish too even though there is no 'checkin' to poolboy instances that i used, here is my test.
Sorry for my english and thanks.

https://github.com/EdoardoLopez/exq_poolboy

**Comment by ananthakumaran** [comment]
> but when the Exq job finish all poolboy instances finish too even though there is no 'checkin' to poolboy instances that i used,

This is because when you do checkout, poolboy [monitors](https://github.com/devinus/poolboy/blob/master/src/poolboy.erl#L212) and automatically [check-in](https://github.com/devinus/poolboy/blob/master/src/poolboy.erl#L250) when the process exit. If you don't want to check-in after exq job is done, do the checkout call from different process

**Comment by EdoardoLopez** [comment]
Oh thanks, for example calling poolboy checkout outside of Exq perform function?

**Comment by ananthakumaran** [comment]
Depends. The question is too broad and I won't be able to give a proper answer without understanding all the details. At this level, this is more of how do I architect the system question.

From Exq perspective, it just creates a new process and calls `apply(worker, :perform, args)`, nothing much to it. I will close the ticket, if you have any specific question related to Exq, I would be happy to answer.
